import {
  Camera,
  Activity,
  Sun,
  Moon,
  Droplets,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  Award,
  BarChart3,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Cloud,
  Cog,
  Coins,
  Copy,
  Download,
  Eye,
  EyeOff,
  File,
  Filter,
  Flag,
  Flame,
  GanttChart,
  GripVertical,
  HeartPulse,
  Home,
  Inbox,
  Info,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link,
  List,
  Lock,
  Mail,
  Minus,
  MoreHorizontal,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  Search,
  Send,
  Shield,
  Sparkles,
  Star,
  StickyNote,
  Tag,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Unlock,
  Upload,
  User,
  Users,
  Wallet,
  Wand2,
  X,
  XCircle,
  Zap,
  Check,
  type LucideProps,
} from 'lucide-react';
import type { IconName } from '@/lib/icons';

type IconComponentProps = {
  name: IconName;
  size?: number;
  stroke?: number;
  className?: string;
};

type LucideComponent = React.ComponentType<LucideProps>;

const iconMap: Record<IconName, LucideComponent> = {
  grid: LayoutGrid,
  coins: Coins,
  check: Check,
  mail: Mail,
  cal: CalendarDays,
  pulse: HeartPulse,
  file: File,
  building: Building2,
  shield: Shield,
  lock: Lock,
  unlock: Unlock,
  cog: Cog,
  drag: GripVertical,
  close: X,
  send: Send,
  wand: Wand2,
  flame: Flame,
  bolt: Zap,
  spark: Sparkles,
  star: Star,
  'star-fill': Star,
  cloud: Cloud,
  plus: Plus,
  minus: Minus,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  dots: MoreHorizontal,
  edit: Pencil,
  trash: Trash2,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  'check-circle': CheckCircle2,
  'x-circle': XCircle,
  info: Info,
  warning: AlertTriangle,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  link: Link,
  copy: Copy,
  eye: Eye,
  'eye-off': EyeOff,
  calendar: Calendar,
  clock: Clock,
  tag: Tag,
  flag: Flag,
  inbox: Inbox,
  list: List,
  board: LayoutDashboard,
  timeline: GanttChart,
  'chart-bar': BarChart3,
  'chart-line': LineChart,
  wallet: Wallet,
  bank: Landmark,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  target: Target,
  award: Award,
  activity: Activity,
  user: User,
  users: Users,
  home: Home,
  pin: Pin,
  archive: Archive,
  note: StickyNote,
  camera: Camera,
  sun: Sun,
  moon: Moon,
  droplet: Droplets,
  nutrition: Activity,
  braosa: Building2,
  verum: Shield,
};

export default function Icon({ name, size = 16, stroke = 1.8, className }: IconComponentProps) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  const fill = name === 'star-fill' ? 'currentColor' : 'none';
  return <LucideIcon size={size} strokeWidth={stroke} className={className} fill={fill} />;
}
